linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - gochecknoinits
    - gochecknoglobals
    - goconst
    - gocyclo
    - dupl
    - funlen

issues:
  exclude-use-default: false
